//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Driver {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleBoards {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleBoards() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Driver.SampleBoards", typeof(SampleBoards).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;MaxFile@&quot;: 3,
        ///	&quot;MaxRank@&quot;: 3,
        ///	&quot;PieceState@&quot;: {
        ///		&quot;head&quot;: {
        ///			&quot;m_Item1&quot;: {
        ///				&quot;_tag&quot;: 0
        ///			},
        ///			&quot;m_Item2&quot;: {
        ///				&quot;File@&quot;: 0,
        ///				&quot;Rank@&quot;: 0
        ///			}
        ///		},
        ///		&quot;tail&quot;: {
        ///			&quot;head&quot;: {
        ///				&quot;m_Item1&quot;: {
        ///					&quot;_tag&quot;: 2
        ///				},
        ///				&quot;m_Item2&quot;: {
        ///					&quot;File@&quot;: 1,
        ///					&quot;Rank@&quot;: 0
        ///				}
        ///			},
        ///			&quot;tail&quot;: {
        ///				&quot;head&quot;: {
        ///					&quot;m_Item1&quot;: {
        ///						&quot;_tag&quot;: 0
        ///					},
        ///					&quot;m_Item2&quot;: {
        ///						&quot;File@&quot;: 2,
        ///						&quot;Rank@&quot;: 0
        ///					}
        ///				},
        ///				&quot;tail&quot;: {
        ///					&quot;head&quot;: {
        ///						&quot;m_Item1&quot;: {
        ///							&quot;_tag&quot;: 3
        ///						},
        ///						&quot;m_Item2&quot;: {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpertBoardOne {
            get {
                return ResourceManager.GetString("ExpertBoardOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;MaxFile@&quot;: 3,
        ///	&quot;MaxRank@&quot;: 3,
        ///	&quot;PieceState@&quot;: {
        ///		&quot;head&quot;: {
        ///			&quot;m_Item1&quot;: {
        ///				&quot;_tag&quot;: 0
        ///			},
        ///			&quot;m_Item2&quot;: {
        ///				&quot;File@&quot;: 0,
        ///				&quot;Rank@&quot;: 0
        ///			}
        ///		},
        ///		&quot;tail&quot;: {
        ///			&quot;head&quot;: {
        ///				&quot;m_Item1&quot;: {
        ///					&quot;_tag&quot;: 0
        ///				},
        ///				&quot;m_Item2&quot;: {
        ///					&quot;File@&quot;: 1,
        ///					&quot;Rank@&quot;: 0
        ///				}
        ///			},
        ///			&quot;tail&quot;: {
        ///				&quot;head&quot;: {
        ///					&quot;m_Item1&quot;: {
        ///						&quot;_tag&quot;: 3
        ///					},
        ///					&quot;m_Item2&quot;: {
        ///						&quot;File@&quot;: 3,
        ///						&quot;Rank@&quot;: 0
        ///					}
        ///				},
        ///				&quot;tail&quot;: {
        ///					&quot;head&quot;: {
        ///						&quot;m_Item1&quot;: {
        ///							&quot;_tag&quot;: 2
        ///						},
        ///						&quot;m_Item2&quot;: {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpertBoardTwo {
            get {
                return ResourceManager.GetString("ExpertBoardTwo", resourceCulture);
            }
        }
    }
}
